name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Vercel build
        run: npx vercel build --prod --token=$VERCEL_TOKEN --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_umNzYj4aX78WbIgY1mj5wNNy
          VERCEL_PROJECT_ID: prj_R6V7y69tauLrpr3gBpD6uYwWD0uQ

      - name: Deploy prebuilt to Vercel
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_umNzYj4aX78WbIgY1mj5wNNy
          VERCEL_PROJECT_ID: prj_R6V7y69tauLrpr3gBpD6uYwWD0uQ
